version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: chai
    versions:
    - 4.2.0
    - 4.3.0
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
